hoilc/scoop-lemon

- bucket/windows-terminal-quake.json
copy from [flyingpie/windows-terminal-quake](https://raw.githubusercontent.com/flyingpie/windows-terminal-quake/master/scoop/windows-terminal-quake.json)
> add windows terminal quake

- bucket/winfi-lite.json
> winfi-lite: fix url

- bucket/foobox-cn.json
> fix foobox-cn

- bucket/tanoshi.json
> add tanoshi

- bucket/xplorer.json
> add xplorer

- bucket/baidupcs-go.json
Reverts hoilc/scoop-lemon#678 as requested
> Revert "add arm64 baidupcs-go"

- bucket/downkyi.json
> fix downkyi autoupdate

- bucket/dnscontrol.json
> fix dnscontrol autoupdate

- bucket/dnscontrol.json
> dnscontrol: deprecate 32bit

- bucket/sylpheed.json
You can add custom themes, and at the moment they don't get carried over
> sylpheed: Add `share\themes` and `etc\gtk-2.0` to `persist`

- bucket/piclist.json
> add piclist

- bucket/alixby.json
> add alixby

- bucket/windows_exporter.json
> windows_exporter: add default textfile dir

- bucket/sakurafrp-launcher.json
> sakurafrp-launcher@3.0.2.0: Fix hash

- bucket/zotero-beta.json
- scripts/zotero/install-zotero-url-protocol.ps1
- scripts/zotero/uninstall-zotero-url-protocol.ps1
> zotero-beta: register url protocol

- bucket/maye-lite.json
> maye-lite: fix extract_dir

- bucket/libportable-floorp.json
> libportable-floorp@11.6.1: Fix hash

- bucket/ffrename.json
[菲菲更名宝贝 之 得意非凡 v5.0 正式版 | 菲菲的家](http://www.ffhome.com/works/1406.html )
一款免费的 windows 文件批量重命名工具，这里打包了一下，以适配 scoop 。
> add ffrename 

- bucket/hybrid.json
> hybrid@2024.01.12.1: Fix hash

- bucket/foobox-cn.json
- bucket/foobox-en.json
> foobox: update to 7.x DUI version

- bucket/oda-file-converter.json
> oda-file-converter@24.12: Fix hash

- bucket/lunatranslator.json
> lunatranslator@2.45.3: Fix hash

- bucket/lunatranslator.json
> lunatranslator@2.45.5: Fix hash

- bucket/lunatranslator.json
> lunatranslator@2.48.1: Fix hash

- bucket/lunatranslator.json
> lunatranslator: fix autoupdate

- bucket/windows-terminal-quake.json
> windows-terminal-quake@2.0.10: Fix hash

- bucket/lucky.json
> lucky@2.8.3: Fix hash

- bucket/wechatbaktool.json
> wechatbaktool@0.9.7.5: Fix hash

- bucket/autok3s.json
> autok3s@0.9.3: Fix hash

- bucket/dataflare.json
> dataflare@20241123: Fix hash

- bucket/dwarfs.json
> dwarfs: fix binary

- bucket/zlibrary.json
> zlibrary: fix installation

- bucket/kite-todo.json
> kite-todo@0.0.19: Fix hash

- bucket/libportable.json
> libportable@55018684: Fix hash

- bucket/libportable-iceweasel.json
> libportable-iceweasel@134.0: Fix hash

- bucket/ffrename.json
> ffrename: re-hosted packages

- bucket/deck.json
> deck@1.43.1: Fix hash

- bucket/rssguard-nightly.json
> rssguard-nightly@devbuild-e78c4a980: Fix hash

- bucket/rssguard-nightly.json
> rssguard-nightly@devbuild-d0697daec: Fix hash

- bucket/lmms-nightly.json
> add lmms-nightly

- bucket/cs-script.json
> cs-script@4.9.1.0: Fix hash

- bucket/cherry-studio.json
[Cherry Studio](https://github.com/CherryHQ/cherry-studio) is an LLM client with about 15k stars.
This manifest support persistent storage of data and I've used it for a long time, working well.
> cherry-studio: add version 0.9.27

- bucket/cherry-studio.json
Hi, this is a minor fix for an error that doesn't affect installation.  
I didn't notice this issue earlier since it only occurs during the very first installation 😂  sorry about that
> cherry-studio: fix for installer script

- bucket/rssguard-nightly.json
> rssguard-nightly@devbuild-f0660c9a5: Fix hash

- bucket/objeck.json
> objeck@2025.2.2: Fix hash

- bucket/azqr.json
> azqr@2.4.0: Fix hash

- bucket/switchfin.json
> switchfin@0.6.2: Fix hash

- bucket/rssguard-nightly.json
> rssguard-nightly@devbuild-e54e7ac13: Fix hash

- bucket/tdengine-client.json
> tdengine-client: fix dlls

- bucket/wincontig.json
> wincontig@5.0.3.1: Fix hash

- bucket/readest.json
> readest@0.9.33: Fix hash

- bucket/xyplorer.json
> add xyplorer

- bucket/pulsarctl.json
> pulsarctl@4.0.4.1: Fix hash

- bucket/opal.json
> opal@1.5.0: Fix hash

- bucket/karing.json
> karing@1.1.2.606: Fix hash

- bucket/windows-update-blocker.json
> windows-update-blocker@1.8: Fix hash

- bucket/bongocat.json
> bongocat@0.5.0: Fix hash

- bucket/flyby11.json
> flyby11@2.6.457: Fix hash

- bucket/usbeam-hosts-editor.json
> usbeam-hosts-editor: fix autoupdate

- bucket/autodarkmode.json
> add autodarkmode

- bucket/keepass.json
Revert https://github.com/ScoopInstaller/Extras/pull/13701
> keepass: install from zip package

- bucket/pulsarctl.json
> pulsarctl@4.0.5.5: Fix hash

- bucket/binjr.json
> binjr@3.23.0: Fix hash

- bucket/openspeedy.json
> openspeedy@1.7.6: Fix hash
